from django.contrib import admin
from djCell.apps.productos.models import TiempoGarantia,Estatus,Marca,Gama,DetallesEquipo,Equipo,TipoIcc,DetallesExpres,Expres,Secciones,MarcaAccesorio,DetallesAccesorio,EstatusAccesorio,Accesorio,NominacionFicha,EstatusFicha,Ficha,TiempoAire, HistorialPreciosEquipos,HistorialPreciosAccesorios,HistorialPreciosExpres

admin.site.register(TiempoGarantia)
admin.site.register(Estatus)
admin.site.register(Marca)
admin.site.register(Gama)
admin.site.register(DetallesEquipo)
admin.site.register(Equipo)
admin.site.register(TipoIcc)
admin.site.register(DetallesExpres)
admin.site.register(Expres)
admin.site.register(Secciones)
admin.site.register(MarcaAccesorio)
admin.site.register(DetallesAccesorio)
admin.site.register(EstatusAccesorio)
admin.site.register(Accesorio)
admin.site.register(NominacionFicha)
admin.site.register(EstatusFicha)
admin.site.register(Ficha)
admin.site.register(TiempoAire)
admin.site.register(HistorialPreciosEquipos)
admin.site.register(HistorialPreciosAccesorios)
admin.site.register(HistorialPreciosExpres)
