# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include
'''from django.conf.urls.defaults import patterns,url'''

urlpatterns=patterns('djCell.interface.contabilidad.views',
	url(r'^$','index_view', name='vista_principal'),

	url(r'^nomina/empleados/nuevo/$','contabilidad_nomina_empleados_nuevo_view', name='vista_contabilidad_nomina_empleados_nuevo'),
	url(r'^nomina/empleados/reporte/$','contabilidad_nomina_empleados_reporte_view', name='vista_contabilidad_nomina_empleados_reporte'),
	url(r'^nomina/empleados/estado_cta/agregar/$','contabilidad_nomina_empleados_estado_cta_agregar_view', name='vista_contabilidad_nomina_empleados_estado_cta_agregar'),
	url(r'^nomina/empleados/estado_cta/historial/$','contabilidad_nomina_empleados_estado_cta_historial_view', name='vista_contabilidad_nomina_empleados_estado_cta_historial'),
	url(r'^nomina/empleados/estado_cta/abonar/$','contabilidad_nomina_empleados_estado_cta_abonar_view', name='vista_contabilidad_nomina_empleados_estado_cta_abonar'),
	url(r'^nomina/usuarios/$','contabilidad_nomina_usuarios_view', name='vista_contabilidad_nomina_usuarios'),
	url(r'^nomina/nueva_nomina/$','contabilidad_nomina_nueva_nomina_view', name='vista_contabilidad_nomina_nueva_nomina'),
	url(r'^nomina/generar_nomina/$','contabilidad_nomina_generar_nomina_view', name='vista_contabilidad_nomina_generar_nomina'),
	url(r'^nomina/nominas/$','contabilidad_nomina_nominas_view', name='vista_contabilidad_nomina_nominas'),
	url(r'^nomina/comisiones/gama/$','contabilidad_nomina_comisiones_gama_view', name='vista_contabilidad_nomina_comisiones_gama'),
	url(r'^nomina/comisiones/actualizar/gama/$','contabilidad_nomina_comisiones_actualizar_gama_view', name='vista_contabilidad_nomina_comisiones_actualizar_gama'),
	url(r'^nomina/comisiones/actualizar/servicios/$','contabilidad_nomina_comisiones_actualizar_servicios_view', name='vista_contabilidad_nomina_comisiones_actualizar_servicios'),
	url(r'^nomina/comisiones/reporte/$','contabilidad_nomina_comisiones_reporte_view', name='vista_contabilidad_nomina_comisiones_reporte'),
	url(r'^polizas/cuentas/$','contabilidad_polizas_cuentas_view', name='vista_contabilidad_polizas_cuentas'),
	url(r'^caja/gastos/$','contabilidad_caja_gastos_view', name='vista_contabilidad_caja_gastos'),
	url(r'^caja/reporte/$','contabilidad_caja_reporte_view', name='vista_contabilidad_caja_reporte'),
	url(r'^caja/ingresos/$','contabilidad_caja_ingresos_view', name='vista_contabilidad_caja_ingresos'),
	url(r'^polizas/ingresos/depositos/$','contabilidad_polizas_ingresos_depositos_view', name='vista_contabilidad_polizas_ingresos_depositos'),
	url(r'^polizas/egresos/poliza_cheques/$','contabilidad_polizas_egresos_poliza_cheques_view', name='vista_contabilidad_polizas_egresos_poliza_cheques'),
	url(r'^polizas/reporte_poliza/$','contabilidad_polizas_reporte_poliza_view', name='vista_contabilidad_polizas_reporte_poliza'),
	url(r'^polizas/lineas_credito/proveedores/nuevo/$','contabilidad_polizas_lineas_credito_proveedores_nuevo_view', name='vista_contabilidad_polizas_lineas_credito_proveedores_nuevo'),
	url(r'^polizas/lineas_credito/proveedores/catalogo/$','contabilidad_polizas_lineas_credito_proveedores_catalogo_view', name='vista_contabilidad_polizas_lineas_credito_proveedores_catalogo'),
	url(r'^polizas/lineas_credito/nueva/$','contabilidad_polizas_lineas_credito_nueva_view', name='vista_contabilidad_polizas_lineas_credito_nueva'),
	url(r'^polizas/lineas_credito/abonos/$','contabilidad_polizas_lineas_credito_abonos_view', name='vista_contabilidad_polizas_lineas_credito_abonos'),
	url(r'^polizas/lineas_credito/historial/$','contabilidad_polizas_lineas_credito_historial_view', name='vista_contabilidad_polizas_lineas_credito_historial'),
	
	#agregados bajo el nuevo modelo de facturas 12:24 19/03/2014
	url(r'^facturacion/facturas/cliente/catalogo/$','contabilidad_facturacion_clientes_catalogo_view', name='catalogo clientes'),
	url(r'^facturacion/facturas/cliente/nuevo/$','contabilidad_facturacion_clientes_nuevo_view', name='nuevos clientes'),

	url(r'^facturacion/facturas/reporte/$','contabilidad_facturacion_facturas_reporte_view', name='reporte facturas'),
	url(r'^facturacion/facturas/agregar/$','contabilidad_facturacion_facturas_agregar_view', name='agregar facturas'),
	url(r'^facturacion/equipo/facturada/$','contabilidad_facturacion_equipo_facturada_view', name='equipos facturados'),
	url(r'^facturacion/equipo/pendiente/$','contabilidad_facturacion_equipo_pendiente_view', name='equipos pendientes a facturar'),
	url(r'^facturacion/express/facturada/$','contabilidad_facturacion_express_facturada_view', name='express facturados'),
	url(r'^facturacion/express/pendiente/$','contabilidad_facturacion_express_pendiente_view', name='express pendientes a facturar'),
	url(r'^facturacion/ficha/facturada/$','contabilidad_facturacion_ficha_facturada_view', name='fichas facturados'),
	url(r'^facturacion/ficha/pendiente/$','contabilidad_facturacion_ficha_pendiente_view', name='fichas pendientes a facturar'),
	url(r'^facturacion/accesorio/facturada/$','contabilidad_facturacion_accesorio_facturada_view', name='accesorios facturados'),
	url(r'^facturacion/accesorio/pendiente/$','contabilidad_facturacion_accesorio_pendiente_view', name='accesorios pendientes a facturar'),
	#***********************************************************

	url(r'^cobranzas/sub_distribuidores/catalogo/$','contabilidad_cobranzas_sub_distribuidores_catalogo_view', name='vista_contabilidad_cobranzas_sub_distribuidores_catalogo'),
	url(r'^cobranzas/sub_distribuidores/historial/$','contabilidad_cobranzas_sub_distribuidores_historial_view', name='vista_contabilidad_cobranzas_sub_distribuidores_historial'),
	url(r'^sucursales/nueva/$','contabilidad_sucursales_nueva_view', name='vista_contabilidad_sucursales_nueva'),
	url(r'^sucursales/sucursales/$','contabilidad_sucursales_sucursales_view', name='vista_contabilidad_sucursales_sucursales'),
	url(r'^sucursales/vendedores/$','contabilidad_sucursales_vendedores_view', name='vista_contabilidad_sucursales_vendedores'),
	url(r'^sucursales/papeletas/$','contabilidad_sucursales_papeletas_view', name='vista_contabilidad_sucursales_papeletas'),
	url(r'^sucursales/arqueos/$','contabilidad_sucursales_arqueos_view', name='vista_contabilidad_sucursales_arqueos'),
	url(r'^sucursales/cortes/verificar/revisar/$','contabilidad_sucursales_cortes_verificar_revisar_view', name='vista_contabilidad_sucursales_cortes_verificar_revisar'),
	url(r'^sucursales/cortes/verificar/diferencias/$','contabilidad_sucursales_cortes_verificar_diferencias_view', name='vista_contabilidad_sucursales_cortes_verificar_diferencias'),
	url(r'^sucursales/cortes/reporte/$','contabilidad_sucursales_cortes_reporte_view', name='vista_contabilidad_sucursales_cortes_reporte'),
	url(r'^sucursales/recargas/reporte/$','contabilidad_sucursales_recargas_reporte_view', name='vista_contabilidad_sucursales_recargas_reporte'),

	url(r'^sucursales/auditorias/nueva/$','contabilidad_sucursales_auditorias_nueva_view', name='vista_contabilidad_sucursales_auditorias_nueva'),
	url(r'^sucursales/auditorias/activas/$','contabilidad_sucursales_auditorias_activas_view', name='vista_contabilidad_sucursales_auditorias_activas'),
	
	url(r'^sucursales/auditorias/determinar/equipo/$','contabilidad_sucursales_auditorias_determinar_equipo_view', name='vista_contabilidad_sucursales_auditorias_determinar'),
	url(r'^sucursales/auditorias/determinar/accesorio/$','contabilidad_sucursales_auditorias_determinar_accesorio_view', name='vista_contabilidad_sucursales_auditorias_determinar'),
	url(r'^sucursales/auditorias/determinar/expres/$','contabilidad_sucursales_auditorias_determinar_expres_view', name='vista_contabilidad_sucursales_auditorias_determinar'),
	url(r'^sucursales/auditorias/determinar/ficha/$','contabilidad_sucursales_auditorias_determinar_ficha_view', name='vista_contabilidad_sucursales_auditorias_determinar'),
	url(r'^sucursales/auditorias/determinar/estado/$','contabilidad_sucursales_auditorias_determinar_estado_view', name='vista_contabilidad_sucursales_auditorias_determinar'),
	
	url(r'^listas/equipos/$','contabilidad_listas_equipos_view', name='vista_contabilidad_listas_equipos'),
	url(r'^listas/accesorios/$','contabilidad_listas_accesorios_view', name='vista_contabilidad_listas_accesorios'),
	url(r'^listas/planes/$','contabilidad_listas_planes_view', name='vista_contabilidad_listas_planes'),

	url(r'^sucursales/auditorias/reportes/$','contabilidad_sucursales_auditorias_reportes_view', name='vista_contabilidad_sucursales_auditorias_reportes'),
	url(r'^reportes/compras/facturas/$','contabilidad_reportes_compras_facturas_view', name='vista_contabilidad_reportes_compras_facturas'),
	url(r'^reportes/compras/costos/$','contabilidad_reportes_compras_costos_view', name='vista_contabilidad_reportes_compras_costos'),
	url(r'^reportes/compras/garantias/$','contabilidad_reportes_compras_garantias_view', name='vista_contabilidad_reportes_compras_garantias'),
	url(r'^reportes/estadisticas/consultar/$','contabilidad_reportes_estadisticas_consultar_view', name='vista_contabilidad_reportes_estadisticas_consultar'),
	url(r'^reportes/existencias/$','contabilidad_reportes_existencias_view', name='vista_contabilidad_reportes_existencias'),
	url(r'^reportes/planes/pendientes/$','contabilidad_reportes_planes_pendientes_view', name='vista_contabilidad_reportes_planes_pendientes'),
	url(r'^reportes/servicios/$','contabilidad_reportes_servicios_view', name='vista_contabilidad_reportes_servicios'),
	url(r'^sucursales/reporte/$','contabilidad_sucursales_reporte_view', name='vista_contabilidad_sucursales_reporte'),
	url(r'^sucursales/vendedores/$','contabilidad_sucursales_vendedores_view', name='vista_contabilidad_sucursales_vendedores'),
	url(r'^sucursales/caja_sucursal/$','contabilidad_sucursales_caja_sucursal_view', name='vista_contabilidad_sucursales_caja_sucursal'),
	url(r'^autorizaciones/cancelaciones/$','contabilidad_autorizaciones_cancelaciones_view', name='vista_contabilidad_autorizaciones_cancelaciones'),
	url(r'^autorizaciones/papelera/$','contabilidad_autorizaciones_papelera_view', name='vista_contabilidad_autorizaciones_papelera'),
	url(r'^auditorias/reportes/realizados/$','contabilidad_reportes_auditorias_realizadas_view', name='vista_auditorias_realizadas_reportes'),
	url(r'^auditorias/reportes/sinrealizar/$','contabilidad_reportes_auditorias_sin_realizar_view', name='vista_auditorias_sin_realizar_reportes'),

	url(r'^usuarios/agregar/$','usuarios_agregar_view', name='vista_usuarios_agregar'),
	url(r'^usuarios/actualizar/$','usuarios_actualizar_view', name='vista_usuarios_actualizar'),
	url(r'^usuarios/vendedores/$','usuarios_vendedores_view', name='vista_usuarios_vendedores'),

	url(r'^gerencia/sancion/agregar/$','gerencia_sancion_agregar_view', name='vista_gerencia_sancion_agregar'),
	url(r'^gerencia/sancion/consultar/$','gerencia_sancion_consultar_view', name='vista_gerencia_sancion_consultar'),
)