from django.conf.urls import patterns, url, include
'''from django.conf.urls.defaults import patterns,url'''

urlpatterns=patterns('djCell.interface.ventas.views',
	url(r'^$','index_view', name='vista_principal'),

	url(r'^ventas/resultado/operacion/$','resultado_operacion_vtas_view', name='vista_resultado_operacion_vtas'),
	url(r'^papeleta/nueva/$','ventas_papeleta_nueva_view', name='vista_papeleta_nueva'),
	url(r'^facturacion/productos/$','ventas_facturacion_productos_view', name='vista_facturacion_productos'),
	url(r'^ventas/menudeo/$','ventas_ventas_menudeo_view', name='vista_ventas_ventas_menudeo'),
	url(r'^ventas/mayoreo_tae/$','ventas_ventas_mayoreo_tae_view', name='vista_ventas_ventas_mayoreo_tae'),
	url(r'^ventas/mayoreo_fichas/$','ventas_ventas_mayoreo_fichas_view', name='vista_ventas_ventas_mayoreo_fichas'),
	url(r'^ventas/apartados/clientes/nuevo/$','ventas_ventas_apartados_clientes_nuevo_view', name='vista_ventas_ventas_apartados_clientes_nuevo'),
	url(r'^ventas/apartados/clientes/catalogo/$','ventas_ventas_apartados_clientes_catalogo_view', name='vista_ventas_ventas_apartados_clientes_catalogo'),
	url(r'^ventas/apartados/nuevo_apartado/$','ventas_ventas_apartados_nuevo_apartado_view', name='vista_ventas_ventas_apartados_nuevo_apartado'),
	url(r'^ventas/apartados/abonos/$','ventas_ventas_apartados_abonos_view', name='vista_ventas_ventas_apartados_abonos'),
	url(r'^ventas/apartados/liquidacion/$','ventas_ventas_apartados_liquidacion_view', name='vista_ventas_ventas_apartados_liquidacion'),
	url(r'^ventas/apartados/cancelacion/$','ventas_ventas_apartados_cancelacion_view', name='vista_ventas_ventas_cancelacion_liquidacion'),
	url(r'^ventas/apartados/historial/$','ventas_ventas_apartados_historial_view', name='vista_ventas_ventas_apartados_historial'),
	url(r'^ventas/pedidos/$','ventas_ventas_pedidos_view', name='vista_ventas_ventas_pedidos'),
	url(r'^ventas/corte_dia/caja/$','ventas_ventas_corte_dia_caja_view', name='vista_ventas_ventas_corte_dia_caja'),
	url(r'^ventas/corte_dia/gastos/$','ventas_ventas_corte_dia_gastos_view', name='vista_ventas_ventas_corte_dia_gastos'),
	url(r'^ventas/corte_dia/cerrar_corte/$','ventas_ventas_corte_dia_cerrar_corte_view', name='vista_ventas_ventas_corte_dia_cerrar_corte'),
	url(r'^servicios/clientes/nuevo/$','ventas_servicios_clientes_nuevo_view', name='vista_ventas_servicios_clientes_nuevo'),
	url(r'^servicios/clientes/catalogo/$','ventas_servicios_clientes_catalogo_view', name='vista_ventas_servicios_clientes_catalogo'),
	url(r'^servicios/cat_reparaciones/$','ventas_servicios_cat_reparaciones_view', name='vista_ventas_servicios_cat_reparaciones'),
	url(r'^servicios/nva_reparacion/$','ventas_servicios_nva_reparacion_view', name='vista_ventas_servicios_nva_reparacion'),
	url(r'^servicios/seguimiento/consultar/$','ventas_servicios_seguimiento_consultar_view', name='vista_ventas_servicios_seguimiento_consultar'),
	url(r'^servicios/garantias/recepcion/$','ventas_servicios_garantias_recepcion_view', name='vista_ventas_servicios_garantias_recepcion'),
	url(r'^servicios/garantias/seguimiento/$','ventas_servicios_garantias_seguimiento_view', name='vista_ventas_servicios_garantias_seguimiento'),
	url(r'^planes_tarifarios/nva_solicitud/$','ventas_planes_tarifarios_nva_solicitud_view', name='vista_ventas_planes_tarifarios_nva_solicitud'),
	url(r'^planes_tarifarios/seguimiento/todos/$','ventas_planes_tarifarios_seguimiento_todos_view', name='vista_ventas_planes_tarifarios_seguimiento_todos'),
	url(r'^planes_tarifarios/seguimiento/consultar/$','ventas_planes_tarifarios_seguimiento_consultar_view', name='vista_ventas_planes_tarifarios_seguimiento_consultar'),
	url(r'^planes_tarifarios/actualizacion/$','ventas_planes_tarifarios_actualizacion_view', name='vista_ventas_planes_tarifarios_actualizacion'),
	url(r'^planes_tarifarios/catalogo/$','ventas_planes_tarifarios_catalogo_view', name='vista_ventas_planes_tarifarios_catalogo'),
	url(r'^portabilidades/agregar/$','ventas_portabilidades_agregar_view', name='vista_ventas_portabilidades_agregar'),
	url(r'^portabilidades/seguimiento/$','ventas_portabilidades_seguimiento_view', name='vista_ventas_portabilidades_seguimiento'),
	url(r'^sucursal/transferencias/$','ventas_sucursal_transferencias_view', name='vista_ventas_sucursal_transferencias'),
	url(r'^sucursal/devoluciones/$','ventas_sucursal_devoluciones_view', name='vista_ventas_sucursal_devoluciones'),
	url(r'^sucursal/existencias/$','ventas_sucursal_existencias_view', name='vista_ventas_sucursal_existencias'),
	url(r'^vendedores/comisiones/$','ventas_vendedores_comisiones_view', name='vista_ventas_vendedores_comisiones'),
	url(r'^vendedores/estado_cuenta/$','ventas_vendedores_estado_cuenta_view', name='vista_ventas_vendedores_estado_cuenta'),
	url(r'^caja/al_dia/$','ventas_caja_al_dia_view', name='vista_ventas_caja_al_dia'),
	url(r'^listas/equipos/$','ventas_listas_equipos_view', name='vista_ventas_listas_equipos'),
	url(r'^listas/accesorios/$','ventas_listas_accesorios_view', name='vista_ventas_listas_accesorios'),
	url(r'^listas/planes/$','ventas_listas_planes_view', name='vista_ventas_listas_planes'),
	url(r'^autorizaciones/cancelaciones/$','ventas_autorizaciones_cancelaciones_view', name='vista_ventas_autorizaciones_cancelaciones'),
	url(r'^papeleta/reporte/$','ventas_papeleta_reporte_view', name='vista_ventas_papeleta_reporte'),


	url(r'^reportes/$','ventas_reportes_view', name='vista_ventas_reportes'),
	#url(r'^eventos/agregar/$','ventas_eventos_agregar_view', name='vista_ventas_eventos_agregar'),
	url(r'^eventos/consultar/$','ventas_eventos_consultar_view', name='vista_ventas_eventos_consultar'),
	url(r'^amonestaciones/agregar/$','ventas_amonestaciones_agregar_view', name='vista_ventas_amonestaciones_agregar'),
	url(r'^amonestaciones/consultar/$','ventas_amonestaciones_consultar_view', name='vista_ventas_amonestaciones_consultar'),
	url(r'^sucursales/reporte/$','ventas_sucursales_reporte_view', name='vista_ventas_sucursales_reporte'),
	url(r'^sucursales/vendedores/$','ventas_sucursales_vendedores_view', name='vista_ventas_sucursales_vendedores'),
	url(r'^reportes/equipos/$','ventas_reportes_equipos_view', name='vista_ventas_reportes_equipos'),
	url(r'^reportes/express/$','ventas_reportes_express_view', name='vista_ventas_reportes_express'),
	url(r'^reportes/planes/$','ventas_reportes_planes_view', name='vista_ventas_reportes_planes'),


)